# Generated by Django 6.0.5 on 2026-06-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaintlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='unique_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
